steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < config.yaml > config.yaml.tmp
      mv config.yaml.tmp config.yaml
  secretEnv: ['WANDB_API_KEY']

- name: "alpine"
  id: "Replace values in the sweep config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < configs/sweep.yaml > configs/sweep.yaml.tmp
      mv configs/sweep.yaml.tmp configs/sweep.yaml
  secretEnv: ['WANDB_PROJECT', 'WANDB_ENTITY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
    cat config.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config', "Replace values in the sweep config"]
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'example-mlops-job',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/vertex_config_secret.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_PROJECT/versions/latest
    env: 'WANDB_PROJECT'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_ENTITY/versions/latest
    env: 'WANDB_ENTITY'