steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < configs/vertex_config_secret.yaml > configs/vertex_config_secret.yaml.tmp
      mv configs/vertex_config_secret.yaml.tmp configs/vertex_config_secret.yaml
  secretEnv: ['WANDB_API_KEY', 'WANDB_PROJECT', 'WANDB_ENTITY']

- name: 'alpine'
  id: "Show training config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
      cat configs/vertex_config_secret.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'secret-insertion',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/vertex_config_secret.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_PROJECT/versions/latest
    env: 'WANDB_PROJECT'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_ENTITY/versions/latest
    env: 'WANDB_ENTITY'