program: src/tweet_sentiment_analysis/train.py
project: ${WANDB_PROJECT}
entity: ${WANDB_ENTITY}
method: random
metric:
  name: eval/loss
  goal: minimize

parameters:
  lr:
    distribution: uniform
    min: 1e-6
    max: 1e-4
  weight_decay:
    distribution: uniform
    min: 0.01
    max: 0.1

run_cap: 2
