program: src/tweet_sentiment_analysis/train.py
method: bayes
metric:
  name: eval/loss
  goal: minimize

parameters:
  lr:
    distribution: uniform
    min: 1e-6
    max: 1e-4
  weight_decay:
    distribution: uniform
    min: 0.01
    max: 0.1