# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/mlops-course-447808/docker-registry/less-sweep-info
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
        - name: WANDB_PROJECT
          value: $WANDB_PROJECT
        - name: WANDB_ENTITY
          value: $WANDB_ENTITY
        - name: WANDB_RUN_COUNT
          value: '5'
        - name: per_device_train_batch_size
          value: '8'
        - name: per_device_eval_batch_size
          value: '8'
        - name: num_train_epochs
          value: '1'
        - name: max_length
          value: '78'
        - name: development_mode
          value: 'No'
